### ISSUE TITLE
Decide the initial version number for projects

### ISSUE THREAD

**Issue by oarrabi** [oarrabi/Guaka#45]
Confirm with Jose

**Comment by goyox86** [comment]
What versioning scheme are we gonna use?

**Comment by oarrabi** [comment]
Semantic?

**Comment by goyox86** [comment]
Cool then start with v0.1.0 so we make our way forward to v1.0.0? I'm a bit rusty on semver though

**Comment by oarrabi** [comment]
Closing this as we already started with version 0.1.0
