### ISSUE TITLE
License for this project

### ISSUE THREAD

**Issue by rbukovansky** [oarrabi/Guaka#50]
Hi, this seems to be very good framework for building CLI applications, but I can't find anywhere how it is licensed (LICENSE file is missing). Could you please add it?

Thanks.

**Comment by oarrabi** [comment]
Hello @rbukovansky thank you for using Guaka :) 
We added the MIT license

**Comment by oarrabi** [comment]
I am going to close this issue. Please do open other issues if anything seems out of place.
As always PRs are always appreciated :)
