### ISSUE TITLE
Pre-release tasks.

### ISSUE THREAD

**Issue by goyox86** [oarrabi/Guaka#54]
- [x] Do we have a static build for Linux for Guaka-Generator?
- [x] Update the site to refer to the Guaka-Generator Github page.
- [x] Maybe a way of installing in Linux systems like https://github.com/junegunn/fzf? (That one is slick)
- [x] Create an account on DO with getguaka@gmail.com and add a droplet move the site there. 
- [x] If we have a installation instruction for Guaka-Generator on the site for MacOS we either remove it or add the Linux one.

//cc @oarrabi

**Comment by oarrabi** [comment]
All done @goyox86
