### ISSUE TITLE
Manually implementing Guaka issue

### ISSUE THREAD

**Issue by pb-z** [oarrabi/Guaka#62]
Followed along with the "Getting Started - Manually implementing Guaka"
But couldn't make it work.
Run `./.build/debug/abc "Hello from cli"` then the issue is:

> hello: 'Hello from cli' is not a hello command. See 'hello --help'.
> 
> Did you mean this?
>   Hello from cli

From `Package.swift`

> import PackageDescription
> 
> let package = Package(name: "abc",
>   dependencies: [
>     .Package(url: "https://github.com/oarrabi/Guaka.git", majorVersion: 0),
>   ]
> )

From main.swift

> import Guaka
> 
> let command = Command(usage: "hello") { _, args in
>   print("You passed \(args) to your Guaka app!")
> }
> 
> command.execute()

After run `swift build`:

> Compile Swift Module 'StringScanner' (5 sources)
> Compile Swift Module 'Guaka' (24 sources)
> Compile Swift Module 'abc' (1 sources)
> Linking ./.build/debug/abc

**Comment by oarrabi** [comment]
Hello @pb-z,

I found the bug and I am working on a fix now.
Thanks for raising it!

**Comment by oarrabi** [comment]
@pb-z This has been fixed. Please delete the `packages` folder and run `swift build` again :)
