### ISSUE TITLE
Add badges

### ISSUE THREAD

**Issue by TofPlay** [oarrabi/Guaka#66]
Below the title please add badges this help a lot. 

If your component is compatible: 
- with SwiftPM add [![SwiftPM compatible](https://img.shields.io/badge/SwiftPM-compatible-brightgreen.svg)](https://github.com/apple/swift-package-manager)

Indicated:
- the Swift version ![Swift Version](https://img.shields.io/badge/Swift-3.0-orange.svg)
- Platforms supported ![Plaforms](https://img.shields.io/badge/Platforms-Linux%20%7C%20macOS%20%7C%20iOS%20%7C%20WatichOS%20%7C%20tvOS-lightgrey.svg)
- License ![License MIT](https://img.shields.io/badge/License-MIT-lightgrey.svg)

**Comment by oarrabi** [comment]
@TofPlay Thanks for raising this. I have a PR ready #67

**Comment by oarrabi** [comment]
Closing this as PR was merged!
