### ISSUE TITLE
homebrew install fails with 404 error

### ISSUE THREAD

**Issue by loyaltyarm** [oarrabi/Guaka#73]
```
$ brew install oarrabi/tap/guaka
==> Installing guaka from oarrabi/tap
==> Downloading https://github.com/oarrabi/Guaka-Generator/releases/download/0.1.1/guaka-generator-0.1.1-darwin-X64.tar.bz2

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "guaka"
Download failed: https://github.com/oarrabi/Guaka-Generator/releases/download/0.1.1/guaka-generator-0.1.1-darwin-X64.tar.bz2
```

The homebrew installation advertised at http://docs.getguaka.com/#getting-started fails with `404 Not Found` error (see above)

Other methods of installation, such as the command below, seem to be working:
`curl https://raw.githubusercontent.com/oarrabi/Guaka-Generator/master/scripts/install.sh -sSf | bash`

**Comment by oarrabi** [comment]
Hello @loyaltyarm, 
Can you please try again I revoked the build yesterday since the version was reported incorrectly.

**Comment by loyaltyarm** [comment]
Nice! Looks like it is working now, thanks!
